version: '3.4'

services:
  productsdb:
    image: postgres

  recipesdb:
    image: postgres

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Product/Product.API/Dockerfile

volumes:
  postgres-products:
  postgres-recipes: